site_name: "ENTSO-E API Python"

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - API Reference: 
    - Items: items.md
    - Balancing: balancing.md
    - Base Classes: base.md
  - Examples: examples.md
  - Development: development.md
  - Issues [Github]: "https://github.com/BerriJ/entsoe-api-py/issues"
  - Source [Github]: "https://github.com/BerriJ/entsoe-api-py"
  - License [Github]: "https://github.com/BerriJ/entsoe-api-py/blob/main/LICENSE"

theme:
  name: "material"
  features:
    - search.share
    - search.highlight
    - search.suggest
    - toc.follow
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: blue
      primary: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: blue
      primary: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options:
          heading_level: 2
          line_length: 80
          show_source: false
          show_root_heading: true
          show_signature: true
          separate_signature: true
          show_signature_annotations: true
          members_order: source
          docstring_section_style: list

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: true



