site_name: "ENTSO-E API Python"

nav:
  - Home: index.md
  - Configuration: configuration.md
  - ENTSOE:
    - ENTSOE Overview: ENTSOE/index.md
    - Market: ENTSOE/market.md
    - Load: ENTSOE/load.md
    - Generation: ENTSOE/generation.md
    - Transmission: ENTSOE/transmission.md
    - Outages: ENTSOE/outages.md
    - Balancing: ENTSOE/balancing.md
    - OMI: ENTSOE/omi.md
  - Package Structure: entsoe_export_tree.md
  - Examples: examples.md
  - Mappings: mappings.md
  - Codes: codes.md
  - Development: development.md
  - Issues [Github]: "https://github.com/BerriJ/entsoe-apy/issues"
  - Source [Github]: "https://github.com/BerriJ/entsoe-apy"
  - License [Github]: "https://github.com/BerriJ/entsoe-apy/blob/main/LICENSE"

theme:
  name: "material"
  features:
    - search.share
    - search.highlight
    - search.suggest
    - navigation.indexes
  palette: 
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      accent: blue
      primary: indigo
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      accent: blue
      primary: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode

plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths: [src]
        options:
          heading_level: 2
          line_length: 80
          show_source: false
          members: true
          show_root_heading: true
          show_signature: true
          separate_signature: true
          show_signature_annotations: true
          members_order: source
          docstring_section_style: list
          merge_init_into_class: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - admonition
  - toc:
      permalink: true
  - pymdownx.pathconverter:
      base_path: .
      relative_path: true
      absolute: false

