name: Lint and Commit

on:
  pull_request:
    branches: [ main, develop ]

jobs:
  lint:
    runs-on: ubuntu-latest 
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    - uses: astral-sh/ruff-action@v3
      with:
          src: "./src"
    - run: ruff check --fix
    - run: ruff format
    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v6
      with:
        commit_message: 'style fixes by ruff'
        file_pattern: '*.py'


